name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install F# Dependencies
        run: dotnet tool install -g FSharp.Formatting

      - name: Run F# Script to Generate HTML
        run: dotnet fsi generate.fsx

      - name: Upload Generated Site
        uses: actions/upload-artifact@v4
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

